name: Terraform Workflow

on:
  push:
    branches:
      - main
env:
  NEWRELIC_ACCOUNT_ID: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
  NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
  NEWRELIC_REGION: ${{ secrets.NEWRELIC_REGION }}

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "~> 1.0"
      
      - name: Terraform Init
        run: terraform init
      
      
      - name: Terraform Plan
        run: terraform plan 
      
      - name: Save Terraform Plan
        uses: actions/upload-artifact@v2
     
      
      - name: Terraform Apply
        run: terraform apply -auto-approve 
