# name: Terraform Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     name: Terraform Actions
#     runs-on: ubuntu-latest
#     env:
#       NEWRELIC_ACCOUNT_ID: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
#       NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
#       NEWRELIC_REGION: ${{ secrets.NEWRELIC_REGION }}
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.0

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan

#       - name: Terraform Apply
#         run: terraform apply -auto-approve
name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Actions
    runs-on: ubuntu-latest
    env:
      NEWRELIC_ACCOUNT_ID: ${{ secrets.NEWRELIC_ACCOUNT_ID }}
      NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
   
      # ROOT_PATH: '${{github.workspace}}/'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        # run: terraform plan -var="NEWRELIC_ACCOUNT_ID=your_account_id" -var="NEWRELIC_API_KEY=your_api_key"
      
        # run: terraform plan -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}"
      - name: Terraform Plan
        run: terraform plan -var="NEWRELIC_ACCOUNT_ID=${{ env.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ env.NEWRELIC_API_KEY }}"



        # working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Apply
        run: terraform apply -auto-approve

     
